name: Export Module.symvers files

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: 下载两份 Module.symvers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download 37446346981 -R ${{ github.repository }} -n Module-symvers-base-k90u -D base
          gh run download 37446416002 -R ${{ github.repository }} -n Module-symvers-cgroupfix-k90u -D cgroupfix
          ls -l base cgroupfix

      - name: 推送到 kmi-report 分支
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "kmi-bot"
          git clone --no-single-branch --depth=1 "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" repo
          cd repo
          git checkout kmi-report || git checkout -b kmi-report
          cp ../base/Module.symvers symvers_base.txt
          cp ../cgroupfix/Module.symvers symvers_cgroupfix.txt
          git add -f symvers_base.txt symvers_cgroupfix.txt
          git commit -m "export full Module.symvers files" || git commit --amend -m "export full Module.symvers files"
          git push -f origin kmi-report
